language: go
sudo: required
services:
  - docker

go:
  - "1.10.x"
  - "1.11.x"

script: go test -v -cover -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)